name: Main CI/CD pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - run: chmod +x ./gradlew
      - name: Build and test
        run: ./gradlew clean test
